import { GoogleGenerativeAI } from '@google/generative-ai';
import { config } from '../config/index.js';
import type { AnalysisResult, NetworkRequest } from '../types/index.js';

export class AiService {
  static isAvailable(): boolean {
    return !!config.geminiApiKey;
  }

  private static getModel() {
    if (!config.geminiApiKey) throw new Error('GEMINI_API_KEY is not configured');
    const client = new GoogleGenerativeAI(config.geminiApiKey);
    return client.getGenerativeModel({ model: 'gemini-2.0-flash-lite' });
  }

  static async getInsights(result: AnalysisResult): Promise<string> {
    const model = this.getModel();

    const failingAudits = result.audits
      .slice(0, 5)
      .map((a) => `- ${a.title}${a.displayValue ? ` (${a.displayValue})` : ''}`)
      .join('\n');

    const prompt = `Web performance expert. Give exactly 3 numbered actionable fixes for this Lighthouse result. Be specific, max 1 sentence each.

Performance:${result.scores.performance} LCP:${(result.metrics.lcp / 1000).toFixed(1)}s TBT:${Math.round(result.metrics.tbt)}ms CLS:${result.metrics.cls.toFixed(2)}
Issues: ${failingAudits || 'none'}`;

    const response = await model.generateContent(prompt);
    return response.response.text();
  }

  /**
   * For each critical resource, returns a Map<url, advice> with a
   * short (≤15 words) optimization tip generated by Gemini.
   */
  static async getResourceAdvice(
    resources: Pick<NetworkRequest, 'url' | 'resourceType' | 'transferSize'>[],
  ): Promise<Map<string, string>> {
    if (resources.length === 0) return new Map();
    const model = this.getModel();

    const list = resources
      .map((r, i) => {
        const kb = Math.round(r.transferSize / 1024);
        let pathname = r.url;
        try { pathname = new URL(r.url).pathname; } catch { /* keep full url */ }
        return `${i + 1}. [${r.resourceType}] ${pathname} (${kb} KB)`;
      })
      .join('\n');

    const prompt = `Web performance expert. For each oversized resource below give exactly one actionable optimization tip (max 15 words). Respond ONLY as a JSON array with objects {index, advice}. No markdown, no prose.

Resources:
${list}`;

    const raw = await model.generateContent(prompt);
    const text = raw.response.text().trim().replace(/^```(?:json)?\n?/, '').replace(/\n?```$/, '');

    try {
      const parsed = JSON.parse(text) as Array<{ index: number; advice: string }>;
      return new Map(
        parsed
          .filter((e) => e.index >= 1 && e.index <= resources.length)
          .map(({ index, advice }) => [resources[index - 1]!.url, advice]),
      );
    } catch {
      console.error('[AI] Failed to parse resource advice JSON:', text.slice(0, 200));
      return new Map();
    }
  }
}
