import type { Server, Socket } from 'socket.io';
import { parseFormFactor } from '../lib/params.js';
import { v4 as uuidv4 } from 'uuid';
import type {
  ServerToClientEvents,
  ClientToServerEvents,
  AnalysisProgress,
  AnalysisResult,
  CategoryPartial,
} from '@perfscope/shared';
import type { InterServerEvents, SocketData } from '../types/socket.js';
import { lighthouseService } from '../services/lighthouse.service.js';
import { attachPreviousRun, enrichWithAi, persistAudit } from '../services/auditPipeline.js';
import { hasSession, extractSessionData } from '../services/authAuditSession.js';
import { findWebsiteByHost } from '../services/websiteLookup.js';
import { recordLoginWall, dropStaleSession } from '../services/loginWall.service.js';
import { findSessionFor, persistCapturedSession } from '../services/sessionStore.js';
import { socketScope } from './scope.js';
import { isValidUrl } from '../lib/url.js';
import { isFetchableTarget } from '../lib/ssrf.js';
import { SessionExpiredError } from '../lib/errors.js';

type TypedServer = Server<ClientToServerEvents, ServerToClientEvents, InterServerEvents, SocketData>;
type TypedSocket = Socket<ClientToServerEvents, ServerToClientEvents, InterServerEvents, SocketData>;

/**
 * Reject a URL this server will not audit — malformed, or pointing into its own network.
 *
 * The empty analysisId is deliberate: the id is generated by this handler *after*
 * validation, so at this point there is nothing to correlate with — and the dashboard's
 * error listener reads only message/code. Was pasted inline in both events, with room for
 * the two copies' wording to drift the way the REST path's already has.
 *
 * The private-network half is a no-op in development, where auditing localhost is the
 * ordinary case — see lib/ssrf.ts for why it is a deployment decision rather than a rule.
 */
async function rejectUnusableUrl(socket: TypedSocket, url: string): Promise<boolean> {
  if (!isValidUrl(url)) {
    socket.emit('analysis:error', { analysisId: '', message: 'Invalid URL format.' });
    return true;
  }
  if (!(await isFetchableTarget(url))) {
    socket.emit('analysis:error', {
      analysisId: '',
      message: 'That address is private or local, and this server will not audit it.',
    });
    return true;
  }
  return false;
}

/** Median precision measures three times and reports the middle run whole. */
const MEDIAN_RUNS = 3;

type PartialCallback = (data: CategoryPartial) => void;

/**
 * The client sends projectId from the page's query string, which goes stale as soon as
 * the user edits the URL in the analyzer: the audit then gets filed under whichever
 * project they happened to open last, or under none at all. Since the project detail page
 * queries strictly by projectId, such an audit shows up on the wrong site or nowhere.
 *
 * The audited URL is the reliable signal, so derive the project from it — a lookup only,
 * never a create. This first tried falling back to `resolveOrCreateProject` when no
 * website matched, on the reasoning that "first sight creates the site" is already the
 * rule everywhere else — but the analyzer is the one place someone deliberately runs a
 * one-off check on a URL they do *not* own or want tracked (a competitor's page, a client's
 * site, anything typed in just to see a number), and silently adding it to their Websites
 * list on read is not what "check this URL" means. The client's own projectId is never
 * consulted at all — an untracked URL's audit is simply untracked (`projectId:
 * undefined`), same as it always was for a URL with no matching site, and an anonymous
 * audit has no owner to file anything under. Explicit tracking stays exactly that: the
 * Websites page, the CLI's own "Save website?" prompt before it ever emits
 * `analysis:start`, or a project-scoped audit whose URL still matches that project.
 */
async function resolveProjectId(
  userId: string | undefined,
  url: string,
): Promise<string | undefined> {
  if (!userId) return undefined;
  try {
    const site = await findWebsiteByHost(userId, url);
    return site ? String(site._id) : undefined;
  } catch {
    return undefined;
  }
}

interface RunAuditParams {
  socket:    TypedSocket;
  url:       string;
  userId:    string | undefined;
  /** Performs the measurement. Gets the id-scoped partial callback and the analysisId. */
  measure:   (onPartial: PartialCallback, analysisId: string) => Promise<AnalysisResult>;
  /** What an expired session should say on this entry path. */
  expiredMessage: (err: SessionExpiredError) => string;
}

/**
 * Everything both entry paths do around the measurement itself: own the analysis id,
 * forward only this audit's events, enrich, persist, flag the login wall, and report.
 *
 * The two handlers were ~70% identical and had already drifted — only `analysis:start`
 * dropped a stale session when one expired, so an `auth-audit` run that failed to
 * authenticate left the session it had just stored in place, ready to be injected into
 * every later audit of that origin.
 */
/**
 * Audits this connection asked to stop.
 *
 * Cancelling kills the worker threads and the Chrome instances they own, and Lighthouse
 * reports that the only way it can: the run in flight throws — "Worker exited with code 1",
 * or, if the browser died first, "Failed to fetch browser webSocket URL from
 * http://127.0.0.1:PORT/json/version". Both are the *sound of the cancellation working*, and
 * both used to be emitted to the client as `analysis:error`.
 *
 * Nothing showed them for a while: the dashboard detaches its listeners before it sends the
 * cancel, so the error arrived at an empty room. That is a timing accident, not a design —
 * the CLI, the extension and any listener that outlives the page (the shell's own, now) all
 * see it, and a person who pressed Stop being told their audit failed with a socket URL is
 * the worst possible reading of "it stopped".
 *
 * Per-connection rather than global: an id belongs to the socket that minted it.
 */
const cancelledByThisSocket = new WeakMap<TypedSocket, Set<string>>();

/**
 * Audits this connection currently has in flight, oldest first.
 *
 * The client cannot always name the audit it wants stopped: the server mints the id and the
 * client only learns it from the first progress event. Press Stop inside that window — which
 * is exactly what someone does when they realise they typed the wrong URL — and there was
 * nothing to send, so nothing stopped and the audit ran to completion.
 *
 * A cancel with no id therefore means "the audit I just started", and this is how the server
 * knows which one that is. Scoped to the socket, so it can only ever stop your own.
 */
const inFlightBySocket = new WeakMap<TypedSocket, string[]>();

function markInFlight(socket: TypedSocket, analysisId: string): void {
  inFlightBySocket.set(socket, [...(inFlightBySocket.get(socket) ?? []), analysisId]);
}

function clearInFlight(socket: TypedSocket, analysisId: string): void {
  const ids = inFlightBySocket.get(socket);
  if (ids) inFlightBySocket.set(socket, ids.filter(id => id !== analysisId));
}

/** The id a cancel is about: the one it named, or this socket's newest run. */
function resolveCancelTarget(socket: TypedSocket, requested: string | null | undefined): string | null {
  if (requested) return requested;
  return inFlightBySocket.get(socket)?.at(-1) ?? null;
}

/**
 * A cancel that arrived before the audit it is about.
 *
 * `analysis:start` is handled asynchronously — the URL is validated and a saved session is
 * looked up before the run is even given an id — while `analysis:cancel` is handled the
 * instant it lands. Stop pressed in the same tick as the start therefore reaches a server
 * that has nothing in flight yet, and used to be dropped on the floor: the audit began a
 * moment later and ran to completion.
 *
 * So an unresolvable cancel is remembered for a moment, and the next run this socket starts
 * checks whether it was already unwanted before it does any work. The window is short by
 * design — this is about a race of milliseconds, not a standing instruction to refuse work.
 */
const CANCEL_AHEAD_WINDOW_MS = 5_000;
const cancelAheadBySocket = new WeakMap<TypedSocket, number>();

function markCancelAhead(socket: TypedSocket): void {
  cancelAheadBySocket.set(socket, Date.now());
}

function consumeCancelAhead(socket: TypedSocket): boolean {
  const at = cancelAheadBySocket.get(socket);
  cancelAheadBySocket.delete(socket);
  return at !== undefined && Date.now() - at < CANCEL_AHEAD_WINDOW_MS;
}

function markCancelled(socket: TypedSocket, analysisId: string): void {
  const ids = cancelledByThisSocket.get(socket) ?? new Set<string>();
  ids.add(analysisId);
  cancelledByThisSocket.set(socket, ids);
}

function wasCancelled(socket: TypedSocket, analysisId: string): boolean {
  return cancelledByThisSocket.get(socket)?.has(analysisId) ?? false;
}

async function runAudit({
  socket, url, userId, measure, expiredMessage,
}: RunAuditParams): Promise<void> {
  // Own the id up front so this socket only forwards its own audit's progress —
  // concurrent audits share the service's event emitter.
  const analysisId = uuidv4();
  markInFlight(socket, analysisId);

  // Stopped before it started — see `cancelAheadBySocket`. Nothing has been emitted yet, so
  // there is nothing to take back: the client asked for silence and gets it.
  if (consumeCancelAhead(socket)) {
    console.log(`[Socket] Audit ${analysisId.slice(0, 8)} stopped before it began`);
    clearInFlight(socket, analysisId);
    return;
  }

  const onProgress = (data: AnalysisProgress) => {
    if (data.analysisId === analysisId) socket.emit('analysis:progress', data);
  };
  const onPartial: PartialCallback = (data) => {
    if (data.analysisId === analysisId) socket.emit('analysis:partial', data);
  };

  lighthouseService.on('progress', onProgress);

  try {
    const result = await measure(onPartial, analysisId);

    // Before the emit, deliberately. The deltas belong to the numbers they annotate: sent
    // afterwards, every score and vital on the page would re-render with an arrow seconds
    // after the reader had already taken the number in. One indexed query buys that.
    const previous = await attachPreviousRun(result, userId);

    // The scores exist now; the user gets them now. Gemini is a second network round
    // trip of 2–4 s that used to sit between the audit finishing and this emit — and
    // for the weeks the model name was dead, that wait bought nothing but a 404.
    socket.emit('analysis:complete', result);

    // Derived from the audited URL — see resolveProjectId for why the client's value
    // cannot be trusted on its own.
    const ownerProjectId = await resolveProjectId(userId, result.url);

    recordLoginWall(userId, result.url, result.authRedirectDetected)
      .catch(err => console.warn('[Website] Login-wall flag failed:', err));

    // Enrich, then persist — the stored audit keeps the commentary the way it always did,
    // and the live client receives it as its own event. `enrichWithAi` never throws for an
    // AI failure (it logs and returns nothing), so a dead model costs a log line, not the save.
    // 'deep' only here: this is the one entry path with a person watching the page the
    // extra commentary decorates.
    const ai = await enrichWithAi(result, { depth: 'deep', userId, previous });

    // Emitted unconditionally, even when every field is empty. The client shows a skeleton
    // from `analysis:complete` until this arrives, so a silent AI phase — no key, a dead
    // model, a page with nothing to say about it — would leave that skeleton up forever.
    // This event means "the AI phase is over", and its contents are secondary.
    socket.emit('analysis:insights', {
      analysisId,
      insights: ai.insights ?? '',
      ...(ai.advice.size > 0 ? { advice: Object.fromEntries(ai.advice) } : {}),
      ...(ai.auditExplanations.size > 0
        ? { auditExplanations: Object.fromEntries(ai.auditExplanations) } : {}),
      ...(Object.keys(ai.metricNotes).length > 0 ? { metricNotes: ai.metricNotes } : {}),
      ...(ai.waterfall ? { waterfall: ai.waterfall } : {}),
    });

    persistAudit(result, userId, ownerProjectId)
      .catch(err => console.warn('[History] Save failed:', err));
  } catch (err) {
    if (err instanceof SessionExpiredError) {
      await dropStaleSession(userId, url, err.loginUrl)
        .catch((e: unknown) => console.warn('[Socket] Failed to drop stale session:', e));
    }

    // A stopped audit is not a failed one. The throw is how the cancellation reached this
    // frame, and the client that asked for it has already moved on.
    if (wasCancelled(socket, analysisId)) {
      console.log(`[Socket] Audit ${analysisId.slice(0, 8)} stopped by the client`);
      cancelledByThisSocket.get(socket)?.delete(analysisId);
      return;
    }

    const message = err instanceof SessionExpiredError
      ? expiredMessage(err)
      : err instanceof Error ? err.message : 'Analysis failed';

    socket.emit('analysis:error', {
      analysisId,
      message,
      ...(err instanceof SessionExpiredError ? { code: err.code } : {}),
    });
  } finally {
    lighthouseService.off('progress', onProgress);
    clearInFlight(socket, analysisId);
  }
}

export function registerAnalysisSocket(io: TypedServer): void {
  io.on('connection', (socket: TypedSocket) => {
    console.log(`[Socket] Connected: ${socket.id}`);

    // The account this connection works on — the team's owner when it named one. Awaited
    // inside each handler so a connection that only listens costs no database read.
    const scopeId = socketScope(socket.handshake.auth);

    socket.on('analysis:start', async (payload) => {
      const userId = await scopeId();
      const { url } = payload;
      const formFactor = parseFormFactor(payload.formFactor);

      if (await rejectUnusableUrl(socket, url)) return;

      console.log(`[Socket] Analysis started: ${url}`);

      const runs = payload.precision === 'median' ? MEDIAN_RUNS : 1;

      // A session captured earlier for this exact origin is injected automatically, so a
      // login-walled page does not have to be re-captured before every run.
      let savedSession = null;
      if (userId) {
        savedSession = await findSessionFor(userId, url)
          .catch(err => { console.warn('[Socket] Failed to load saved session:', err); return null; });
        if (savedSession) console.log(`[Socket] Using saved session for ${url}`);
      }

      await runAudit({
        socket, url, userId,
        measure: (onPartial, analysisId) => savedSession
          ? lighthouseService.analyzeWithInjectedSession(url, savedSession, onPartial, { formFactor, runs, analysisId })
          // `captureElements` only here, and only on this branch: a person is watching this
          // page, and the crops it produces are what turn a selector in the audit list into
          // something they can recognise. The session path measures through a live browser
          // rather than the worker and has no cropping step.
          : lighthouseService.analyzeStreaming(url, onPartial, { formFactor, runs, analysisId, captureElements: true }),
        expiredMessage: err => err.message,
      });
    });

    socket.on('analysis:cancel', (payload) => {
      // An unnamed cancel is about this socket's newest run — see `inFlightBySocket`.
      const analysisId = resolveCancelTarget(socket, payload.analysisId);
      if (!analysisId) {
        // The start has not been processed yet; leave a note for it.
        markCancelAhead(socket);
        return;
      }

      // Marked before the kill, not after: terminating the workers is what makes the run
      // throw, and the throw can reach `runAudit`'s catch before this handler returns.
      markCancelled(socket, analysisId);
      lighthouseService.cancelAnalysis(analysisId);
    });

    socket.on('auth-audit:start', async (payload) => {
      const userId = await scopeId();
      const { sessionId, url, context } = payload;
      const formFactor = parseFormFactor(payload.formFactor);

      if (await rejectUnusableUrl(socket, url)) return;

      if (!hasSession(sessionId)) {
        socket.emit('analysis:error', {
          analysisId: '',
          message: 'Auth session not found or expired. Please start over.',
        });
        return;
      }

      // The visible browser stays open for re-use after the harvest.
      const sessionData = await extractSessionData(sessionId);

      if (userId) {
        persistCapturedSession(userId, url, sessionData, context === 'competitor' ? 'competitor' : 'own')
          .catch(err => console.warn('[Socket] Failed to persist captured session:', err));
      }

      await runAudit({
        socket, url, userId,
        measure: (onPartial, analysisId) =>
          lighthouseService.analyzeWithInjectedSession(url, sessionData, onPartial, { formFactor, analysisId }),
        expiredMessage: () =>
          'The captured session did not authenticate — log in inside the opened browser, then run the audit again.',
      });
    });

    socket.on('disconnect', (reason: string) => {
      console.log(`[Socket] Disconnected: ${socket.id} (${reason})`);
    });
  });
}
