import type { Server, Socket } from 'socket.io';
import { parseFormFactor } from '../lib/params.js';
import { v4 as uuidv4 } from 'uuid';
import type {
  ServerToClientEvents,
  ClientToServerEvents,
  AnalysisProgress,
  AnalysisResult,
  CategoryPartial,
} from '@perfscope/shared';
import type { InterServerEvents, SocketData } from '../types/socket.js';
import { lighthouseService } from '../services/lighthouse.service.js';
import { enrichWithAi, persistAudit } from '../services/auditPipeline.js';
import { hasSession, extractSessionData } from '../services/authAuditSession.js';
import { findWebsiteByHost } from '../services/websiteLookup.js';
import { recordLoginWall, dropStaleSession } from '../services/loginWall.service.js';
import { findSessionFor, persistCapturedSession } from '../services/sessionStore.js';
import { userIdFromToken } from '../middleware/auth.middleware.js';
import { isValidUrl } from '../lib/url.js';
import { SessionExpiredError } from '../lib/errors.js';

type TypedServer = Server<ClientToServerEvents, ServerToClientEvents, InterServerEvents, SocketData>;
type TypedSocket = Socket<ClientToServerEvents, ServerToClientEvents, InterServerEvents, SocketData>;

/**
 * Reject a malformed URL before doing anything else.
 *
 * The empty analysisId is deliberate: the id is generated by this handler *after*
 * validation, so at this point there is nothing to correlate with — and the dashboard's
 * error listener reads only message/code. Was pasted inline in both events, with room for
 * the two copies' wording to drift the way the REST path's already has.
 */
function rejectInvalidUrl(socket: TypedSocket, url: string): boolean {
  if (isValidUrl(url)) return false;
  socket.emit('analysis:error', { analysisId: '', message: 'Invalid URL format.' });
  return true;
}

/** Median precision measures three times and reports the middle run whole. */
const MEDIAN_RUNS = 3;

type PartialCallback = (data: CategoryPartial) => void;

/**
 * The client sends projectId from the page's query string, which goes stale as soon as
 * the user edits the URL in the analyzer: the audit then gets filed under whichever
 * project they happened to open last, or under none at all. Since the project detail page
 * queries strictly by projectId, such an audit shows up on the wrong site or nowhere.
 *
 * The audited URL is the reliable signal, so derive the project from it — a lookup only,
 * never a create. This first tried falling back to `resolveOrCreateProject` when no
 * website matched, on the reasoning that "first sight creates the site" is already the
 * rule everywhere else — but the analyzer is the one place someone deliberately runs a
 * one-off check on a URL they do *not* own or want tracked (a competitor's page, a client's
 * site, anything typed in just to see a number), and silently adding it to their Websites
 * list on read is not what "check this URL" means. The client's own projectId is never
 * consulted at all — an untracked URL's audit is simply untracked (`projectId:
 * undefined`), same as it always was for a URL with no matching site, and an anonymous
 * audit has no owner to file anything under. Explicit tracking stays exactly that: the
 * Websites page, the CLI's own "Save website?" prompt before it ever emits
 * `analysis:start`, or a project-scoped audit whose URL still matches that project.
 */
async function resolveProjectId(
  userId: string | undefined,
  url: string,
): Promise<string | undefined> {
  if (!userId) return undefined;
  try {
    const site = await findWebsiteByHost(userId, url);
    return site ? String(site._id) : undefined;
  } catch {
    return undefined;
  }
}

interface RunAuditParams {
  socket:    TypedSocket;
  url:       string;
  userId:    string | undefined;
  /** Performs the measurement. Gets the id-scoped partial callback and the analysisId. */
  measure:   (onPartial: PartialCallback, analysisId: string) => Promise<AnalysisResult>;
  /** What an expired session should say on this entry path. */
  expiredMessage: (err: SessionExpiredError) => string;
}

/**
 * Everything both entry paths do around the measurement itself: own the analysis id,
 * forward only this audit's events, enrich, persist, flag the login wall, and report.
 *
 * The two handlers were ~70% identical and had already drifted — only `analysis:start`
 * dropped a stale session when one expired, so an `auth-audit` run that failed to
 * authenticate left the session it had just stored in place, ready to be injected into
 * every later audit of that origin.
 */
async function runAudit({
  socket, url, userId, measure, expiredMessage,
}: RunAuditParams): Promise<void> {
  // Own the id up front so this socket only forwards its own audit's progress —
  // concurrent audits share the service's event emitter.
  const analysisId = uuidv4();

  const onProgress = (data: AnalysisProgress) => {
    if (data.analysisId === analysisId) socket.emit('analysis:progress', data);
  };
  const onPartial: PartialCallback = (data) => {
    if (data.analysisId === analysisId) socket.emit('analysis:partial', data);
  };

  lighthouseService.on('progress', onProgress);

  try {
    const result = await measure(onPartial, analysisId);

    // The scores exist now; the user gets them now. Gemini is a second network round
    // trip of 2–4 s that used to sit between the audit finishing and this emit — and
    // for the weeks the model name was dead, that wait bought nothing but a 404.
    socket.emit('analysis:complete', result);

    // Derived from the audited URL — see resolveProjectId for why the client's value
    // cannot be trusted on its own.
    const ownerProjectId = await resolveProjectId(userId, result.url);

    recordLoginWall(userId, result.url, result.authRedirectDetected)
      .catch(err => console.warn('[Website] Login-wall flag failed:', err));

    // Enrich, then persist — the stored audit keeps the commentary the way it always did,
    // and the live client receives it as its own event. `enrichWithAi` never throws for an
    // AI failure (it logs and returns nothing), so a dead model costs a log line, not the save.
    // 'deep' only here: this is the one entry path with a person watching the page the
    // extra commentary decorates.
    const ai = await enrichWithAi(result, { depth: 'deep', userId });

    // Emitted unconditionally, even when every field is empty. The client shows a skeleton
    // from `analysis:complete` until this arrives, so a silent AI phase — no key, a dead
    // model, a page with nothing to say about it — would leave that skeleton up forever.
    // This event means "the AI phase is over", and its contents are secondary.
    socket.emit('analysis:insights', {
      analysisId,
      insights: ai.insights ?? '',
      ...(ai.advice.size > 0 ? { advice: Object.fromEntries(ai.advice) } : {}),
      ...(ai.auditExplanations.size > 0
        ? { auditExplanations: Object.fromEntries(ai.auditExplanations) } : {}),
      ...(Object.keys(ai.metricNotes).length > 0 ? { metricNotes: ai.metricNotes } : {}),
      ...(ai.waterfall ? { waterfall: ai.waterfall } : {}),
    });

    persistAudit(result, userId, ownerProjectId)
      .catch(err => console.warn('[History] Save failed:', err));
  } catch (err) {
    if (err instanceof SessionExpiredError) {
      await dropStaleSession(userId, url, err.loginUrl)
        .catch((e: unknown) => console.warn('[Socket] Failed to drop stale session:', e));
    }

    const message = err instanceof SessionExpiredError
      ? expiredMessage(err)
      : err instanceof Error ? err.message : 'Analysis failed';

    socket.emit('analysis:error', {
      analysisId,
      message,
      ...(err instanceof SessionExpiredError ? { code: err.code } : {}),
    });
  } finally {
    lighthouseService.off('progress', onProgress);
  }
}

export function registerAnalysisSocket(io: TypedServer): void {
  io.on('connection', (socket: TypedSocket) => {
    console.log(`[Socket] Connected: ${socket.id}`);

    const userId = userIdFromToken((socket.handshake.auth as { token?: string }).token);

    socket.on('analysis:start', async (payload) => {
      const { url } = payload;
      const formFactor = parseFormFactor(payload.formFactor);

      if (rejectInvalidUrl(socket, url)) return;

      console.log(`[Socket] Analysis started: ${url}`);

      const runs = payload.precision === 'median' ? MEDIAN_RUNS : 1;

      // A session captured earlier for this exact origin is injected automatically, so a
      // login-walled page does not have to be re-captured before every run.
      let savedSession = null;
      if (userId) {
        savedSession = await findSessionFor(userId, url)
          .catch(err => { console.warn('[Socket] Failed to load saved session:', err); return null; });
        if (savedSession) console.log(`[Socket] Using saved session for ${url}`);
      }

      await runAudit({
        socket, url, userId,
        measure: (onPartial, analysisId) => savedSession
          ? lighthouseService.analyzeWithInjectedSession(url, savedSession, onPartial, { formFactor, runs, analysisId })
          : lighthouseService.analyzeStreaming(url, onPartial, { formFactor, runs, analysisId }),
        expiredMessage: err => err.message,
      });
    });

    socket.on('analysis:cancel', (payload) => {
      lighthouseService.cancelAnalysis(payload.analysisId);
    });

    socket.on('auth-audit:start', async (payload) => {
      const { sessionId, url, context } = payload;
      const formFactor = parseFormFactor(payload.formFactor);

      if (rejectInvalidUrl(socket, url)) return;

      if (!hasSession(sessionId)) {
        socket.emit('analysis:error', {
          analysisId: '',
          message: 'Auth session not found or expired. Please start over.',
        });
        return;
      }

      // The visible browser stays open for re-use after the harvest.
      const sessionData = await extractSessionData(sessionId);

      if (userId) {
        persistCapturedSession(userId, url, sessionData, context === 'competitor' ? 'competitor' : 'own')
          .catch(err => console.warn('[Socket] Failed to persist captured session:', err));
      }

      await runAudit({
        socket, url, userId,
        measure: (onPartial, analysisId) =>
          lighthouseService.analyzeWithInjectedSession(url, sessionData, onPartial, { formFactor, analysisId }),
        expiredMessage: () =>
          'The captured session did not authenticate — log in inside the opened browser, then run the audit again.',
      });
    });

    socket.on('disconnect', (reason: string) => {
      console.log(`[Socket] Disconnected: ${socket.id} (${reason})`);
    });
  });
}
