import { GoogleGenerativeAI } from '@google/generative-ai';
import { createHash } from 'node:crypto';
import { config } from '../config/index.js';
import { rateVital, VITAL_THRESHOLDS } from '@perfscope/shared';
import type { AnalysisResult, NetworkRequest, AiAdvice, AiMetricNotes, CoreWebVitals } from '@perfscope/shared';

/** Identical prompt in, identical text out — so retries and re-saves cost nothing. */
const CACHE_TTL_MS = 6 * 60 * 60_000;
const CACHE_MAX    = 300;

export class AiService {
  static isAvailable(): boolean {
    return !!config.geminiApiKey;
  }

  /**
   * Google's rolling alias, not a pinned version. `gemini-2.0-flash-lite` was retired and
   * every audit logged a 404 for weeks with nobody noticing; when this was fixed,
   * `gemini-2.5-flash-lite` was *listed* by the models endpoint and already 404ing too.
   * The alias moves with them. If Google ever drops it, ListModels is the place to look.
   */
  private static readonly MODEL = 'gemini-flash-lite-latest';

  private static getModel() {
    if (!config.geminiApiKey) throw new Error('GEMINI_API_KEY is not configured');
    const client = new GoogleGenerativeAI(config.geminiApiKey);
    return client.getGenerativeModel({ model: this.MODEL });
  }

  private static readonly cache = new Map<string, { text: string; expiresAt: number }>();

  /**
   * The single door to Gemini. Every prompt goes through here so the fence-stripping,
   * the cache and the deadline are written once rather than per method.
   *
   * `timeoutMs` matters for the callers a person is waiting behind — an alert must go out
   * whether or not the model has anything to say about it.
   */
  private static async generate(prompt: string, opts: { timeoutMs?: number } = {}): Promise<string> {
    const key = createHash('sha256').update(this.MODEL).update('\0').update(prompt).digest('hex');
    const hit = this.cache.get(key);
    if (hit && hit.expiresAt > Date.now()) return hit.text;

    const model = this.getModel();
    const call  = model.generateContent(prompt).then(r => r.response.text());

    const raw = opts.timeoutMs === undefined ? await call : await Promise.race([
      call,
      new Promise<never>((_, reject) =>
        setTimeout(() => reject(new Error(`Gemini timed out after ${opts.timeoutMs}ms`)), opts.timeoutMs).unref()),
    ]);

    // Models fence JSON even when told not to; strip it once, here, for everyone.
    const text = raw.trim().replace(/^```(?:json)?\n?/, '').replace(/\n?```$/, '');

    // An empty answer is not an answer worth remembering. Caching one would turn a single
    // blank or refused response into six hours of silence for that exact prompt, and every
    // caller treats empty as "nothing to say" rather than "ask again".
    if (!text) return text;

    if (this.cache.size >= CACHE_MAX) {
      const now = Date.now();
      for (const [k, v] of this.cache) if (v.expiresAt <= now) this.cache.delete(k);
      if (this.cache.size >= CACHE_MAX) this.cache.delete(this.cache.keys().next().value!);
    }
    this.cache.set(key, { text, expiresAt: Date.now() + CACHE_TTL_MS });
    return text;
  }

  /** Parse a fenced-or-bare JSON reply; `null` rather than a throw when the model rambles. */
  private static parseJson<T>(text: string, label: string): T | null {
    try {
      return JSON.parse(text) as T;
    } catch {
      console.error(`[AI] Failed to parse ${label} JSON:`, text.slice(0, 200));
      return null;
    }
  }

  static async getInsights(result: AnalysisResult): Promise<string> {
    const failingAudits = result.audits
      .slice(0, 5)
      .map((a) => `- ${a.title}${a.displayValue ? ` (${a.displayValue})` : ''}`)
      .join('\n');

    const prompt = `Web performance expert. Give exactly 3 numbered actionable fixes for this Lighthouse result. Be specific, max 1 sentence each.

Performance:${result.scores.performance} LCP:${(result.metrics.lcp / 1000).toFixed(1)}s TBT:${Math.round(result.metrics.tbt)}ms CLS:${result.metrics.cls.toFixed(2)}
Issues: ${failingAudits || 'none'}`;

    return this.generate(prompt);
  }

  /**
   * For each critical resource, returns a Map<url, advice> with a
   * short (≤15 words) optimization tip generated by Gemini.
   */
  static async getResourceAdvice(
    resources: Pick<NetworkRequest, 'url' | 'resourceType' | 'transferSize'>[],
  ): Promise<Map<string, string>> {
    if (resources.length === 0) return new Map();

    const list = resources
      .map((r, i) => {
        const kb = Math.round(r.transferSize / 1024);
        let pathname = r.url;
        try { pathname = new URL(r.url).pathname; } catch { /* keep full url */ }
        return `${i + 1}. [${r.resourceType}] ${pathname} (${kb} KB)`;
      })
      .join('\n');

    const prompt = `Web performance expert. For each oversized resource below give exactly one actionable optimization tip (max 15 words). Respond ONLY as a JSON array with objects {index, advice}. No markdown, no prose.

Resources:
${list}`;

    const parsed = this.parseJson<Array<{ index: number; advice: string }>>(
      await this.generate(prompt), 'resource advice');
    if (!Array.isArray(parsed)) return new Map();

    return new Map(
      parsed
        .filter((e) => e.index >= 1 && e.index <= resources.length && typeof e.advice === 'string')
        .map(({ index, advice }) => [resources[index - 1]!.url, advice.slice(0, 200)]),
    );
  }
  // ─── Deepening one audit ────────────────────────────────────────────────────

  /** Explaining a passing audit costs a token and says nothing. */
  private static readonly AUDIT_LIMIT = 8;

  /**
   * Why each failing audit fails *on this page*, and the first thing to do about it.
   *
   * One call for every audit, never one per audit: eight round trips would cost eight
   * times the latency and money to say things the model can say together, with more
   * context, in one.
   */
  static async getAuditExplanations(result: AnalysisResult): Promise<Map<string, string>> {
    const failing = result.audits
      .filter((a) => a.score !== null && a.score < 0.9)
      .slice(0, this.AUDIT_LIMIT);
    if (failing.length === 0) return new Map();

    const list = failing
      .map((a) => `${a.id} | ${a.title}${a.displayValue ? ` | ${a.displayValue}` : ''}`)
      .join('\n');

    const prompt = `Web performance expert. For each failing Lighthouse audit below, say why it likely fails on THIS page and the first concrete step to fix it. Max 25 words each. Respond ONLY as a JSON array of {id, explanation}. No markdown, no prose.

Page: ${result.url} (performance ${result.scores.performance})
Audits (id | title | value):
${list}`;

    const parsed = this.parseJson<Array<{ id: string; explanation: string }>>(
      await this.generate(prompt), 'audit explanations');
    if (!Array.isArray(parsed)) return new Map();

    const wanted = new Set(failing.map((a) => a.id));
    return new Map(
      parsed
        .filter((e) => wanted.has(e.id) && typeof e.explanation === 'string')
        .map(({ id, explanation }) => [id, explanation.slice(0, 300)]),
    );
  }

  /**
   * Per-vital notes and a narrative of how the page actually loaded.
   *
   * Combined into one call because both describe the same load, and because the waterfall
   * is most of the context the metric notes need anyway.
   *
   * Which vitals are "not good" is decided here, from the shared thresholds — the model is
   * told what to explain, never asked to judge whether a number is acceptable.
   */
  static async getPageNarrative(
    result: AnalysisResult,
  ): Promise<{ metrics: AiMetricNotes; waterfall: string | null }> {
    const empty = { metrics: {} as AiMetricNotes, waterfall: null };

    const keys = Object.keys(VITAL_THRESHOLDS).filter(
      (k): k is keyof CoreWebVitals => k in result.metrics,
    );
    const poor = keys.filter((k) => rateVital(k, result.metrics[k]) !== 'good');

    const requests = result.resources?.requests ?? [];
    const heaviest = [...requests]
      .sort((a, b) => b.transferSize - a.transferSize)
      .slice(0, 5)
      .map((r, i) => {
        let path = r.url;
        try { path = new URL(r.url).pathname; } catch { /* keep the whole url */ }
        return `${i + 1}. [${r.resourceType}] ${path} ${Math.round(r.transferSize / 1024)}KB start ${Math.round(r.startTime)}ms ttfb ${Math.round(r.ttfb)}ms`;
      })
      .join('\n');

    if (poor.length === 0 && heaviest.length === 0) return empty;

    const prompt = `Web performance expert. Two things about this page load.

1. For each metric listed, one note (max 20 words) on what is causing it here.
2. "waterfall": 2-3 sentences narrating how this page loaded — the sequence, what blocked what.

Respond ONLY as JSON: {"metrics": {"<key>": "<note>"}, "waterfall": "<prose>"}. No markdown.

Page: ${result.url}
Metrics needing a note: ${poor.length ? poor.map(k => `${k}=${Math.round(result.metrics[k] * 1000) / 1000}`).join(' ') : '(none)'}
Requests: ${requests.length} total, ${result.resources?.thirdPartyRequests?.length ?? 0} third-party requests
Heaviest:
${heaviest || '(no request data)'}`;

    const parsed = this.parseJson<{ metrics?: Record<string, unknown>; waterfall?: unknown }>(
      await this.generate(prompt), 'page narrative');
    if (!parsed) return empty;

    const metrics: AiMetricNotes = {};
    for (const k of poor) {
      const note = parsed.metrics?.[k];
      if (typeof note === 'string' && note.trim()) metrics[k] = note.slice(0, 200);
    }
    const waterfall = typeof parsed.waterfall === 'string' && parsed.waterfall.trim()
      ? parsed.waterfall.slice(0, 600)
      : null;

    return { metrics, waterfall };
  }

  // ─── Surfaces outside the analyzer ──────────────────────────────────────────

  /**
   * One or two sentences to go out with an alert.
   *
   * Time-boxed: an alert that is late is nearly as bad as one that never arrives, so the
   * note is whatever the model managed inside the deadline, or nothing.
   */
  static async getAlertNote(
    alert: { kind: string; url: string; formFactor: string | null; lines: string[] },
    opts: { timeoutMs?: number } = {},
  ): Promise<string | null> {
    const prompt = `Web performance expert. A monitoring alert just fired. In at most 2 sentences, plain text, no markdown: what this likely means for users, and the first thing to check.

Alert: ${alert.kind}
Page: ${alert.url} (${alert.formFactor ?? 'desktop'})
Findings:
${alert.lines.map(l => `- ${l}`).join('\n')}`;

    const text = (await this.generate(prompt, opts)).trim();
    return text || null;
  }

  /** The editor's note at the top of the weekly digest. */
  static async getDigestSummary(data: {
    sites: number; audits: number; avgScore: number | null; prevAvgScore: number | null;
    regressions: number; breaches: number;
    slowest: Array<{ url: string; score: number; lcp: number }>;
  }): Promise<string | null> {
    const prompt = `Web performance expert writing the opening note of a weekly report. At most 3 sentences, plain text, no markdown: the biggest movement this week and the one page most worth fixing next. Do not repeat the numbers verbatim — interpret them.

Sites: ${data.sites}, audits run: ${data.audits}
Average score: ${data.avgScore ?? 'n/a'} (previous week: ${data.prevAvgScore ?? 'n/a'})
Regressions: ${data.regressions}, budget breaches: ${data.breaches}
Slowest pages:
${data.slowest.map(r => `- ${r.url} score ${r.score} lcp ${Math.round(r.lcp)}ms`).join('\n') || '- (none)'}`;

    const text = (await this.generate(prompt)).trim();
    return text || null;
  }


  /**
   * The advisor's answer to "what should I do next?".
   *
   * Structured rather than prose because this drives a panel that is on screen all the
   * time: a headline short enough to read at a glance, and up to three concrete steps.
   * Anything longer becomes wallpaper — the whole point is that it is worth reading.
   */
  static async getAdvice(input: {
    /** What the user is looking at, so the advice is about that and not the whole account. */
    scope: string;
    /** Pre-formatted lines of context. The caller decides what is worth showing. */
    lines: string[];
  }): Promise<AiAdvice | null> {
    if (input.lines.length === 0) return null;

    const prompt = `You are a web performance advisor embedded in a monitoring tool. The user is looking at: ${input.scope}.

Answer ONLY with JSON: {"headline": string, "steps": [{"title": string, "detail": string}]}

- headline: at most 12 words, the single most useful thing to say right now.
- steps: 1 to 3, ordered by what to do first. title at most 8 words, detail at most 25 words and concrete.
- If everything looks healthy, say so plainly and suggest what to watch, rather than inventing problems.
- Refer to specific sites and numbers from the context. Never repeat a number without interpreting it.

Context:
${input.lines.join('\n')}`;

    const raw = await this.generate(prompt);
    const parsed = this.parseJson<{ headline?: unknown; steps?: unknown }>(raw, 'advice');
    if (!parsed || typeof parsed.headline !== 'string' || !parsed.headline.trim()) return null;

    const steps = Array.isArray(parsed.steps) ? parsed.steps : [];
    return {
      headline: parsed.headline.trim().slice(0, 140),
      steps: steps
        .filter((s): s is { title: string; detail: string } =>
          !!s && typeof (s as { title?: unknown }).title === 'string'
              && typeof (s as { detail?: unknown }).detail === 'string')
        .slice(0, 3)
        .map(s => ({ title: s.title.trim().slice(0, 80), detail: s.detail.trim().slice(0, 220) })),
    };
  }

  /** The verdict on a saved head-to-head comparison. */
  static async getCompareVerdict(entry: {
    sourceUrl: string; targetUrl: string;
    source:     { scores: Record<string, number>; metrics: Record<string, number> };
    competitor: { scores: Record<string, number>; metrics: Record<string, number> };
  }): Promise<string | null> {
    const side = (s: { scores: Record<string, number>; metrics: Record<string, number> }) =>
      `perf ${s.scores['performance'] ?? '?'} lcp ${Math.round(s.metrics['lcp'] ?? 0)}ms tbt ${Math.round(s.metrics['tbt'] ?? 0)}ms cls ${s.metrics['cls'] ?? 0}`;

    const prompt = `Web performance expert. Two sites were just measured head to head. In 2-3 sentences, plain text, no markdown: who is faster overall, the single biggest gap, and the one metric the slower site should attack first.

Yours (${entry.sourceUrl}): ${side(entry.source)}
Rival (${entry.targetUrl}): ${side(entry.competitor)}`;

    const text = (await this.generate(prompt)).trim();
    return text || null;
  }
}
